version: "3.9"

services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/production/django/Dockerfile
        command: /start
        image: authors-haven-api
        env_file:
            - ./.envs/.production/.django
            - ./.envs/.production/.postgres
        depends_on:
            - redis


    redis:
        image: redis:6-alpine


    rabbitmq:
        image: rabbitmq:3-management
        env_file:
            - ./.envs/.production/.django


    celery_worker:
        <<: *api
        image: authors-haven-celeryworker
        command: /start-celeryworker


    flower:
        <<: *api
        image: authors-haven-flower
        command: /start-flower
